name: Main CI
on:
  push:
# push:
#   tags:
#     - "v*.*.*"
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# Added tag

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Set debug vars
        env: { CONTENT: "${{ toJson(steps) }}" }
        run: "echo $CONTENT"
